### ISSUE TITLE
problem with png and gps metadata

### ISSUE THREAD

**Issue by kax17** [Alamantus/GooglePhotosExportOrganizer#15]
png images (screenshots) didn't merged with their json files, also the jpg that merged successfully lost their gps metadata in the process

**Comment by Alamantus** [comment]
@kax17 Unfortunately, I only set up the app to merge the JSON data into JPEG files because I didn't (and still don't) know how PNGs handle metadata like that.

As for the JPEG metadata, can you elaborate a little more? Is there any GPS metadata at all (i.e. incorrect data) or is it just empty? Are you able to check the JSON file associated with one of the images that lost its data and see if it includes the correct GPS data? The way the app works is that it just _assumes_ the JSON data from the Google Takeout has all the correct and relevant data and just shoves it into the JPEG's Exif data section, so if the JSON is wrong, then the final result will be wrong.

It may be worth trying the organize process again on a re-extracted Takeout, but leaving the Copy Metadata function off to see if the data in the original JPEG files are correct—sometimes the files exported from Google do have the correct metadata and merging the JSON in is just a failsafe.
