### ISSUE TITLE
Linux client doesn't create output

### ISSUE THREAD

**Issue by ferreric** [Alamantus/GooglePhotosExportOrganizer#5]
Hi, I'm on Manjaro and I have trouble using your tool. I used it on an exFAT external drive and it failed to create output.

Same results using ext4 as either source or target.

Using an SMB share as source and exFAT as target at least resulted in creating a what seems to be meaningful folder structure. Problem is that those folders are all empty. Still, the SMB process (comig from a raspberry pi as server) took quite long so it looked busy combing thru 90 GB of pictures. What else can I try?

Also, Manjaro / Thunar fails to recognize your executable file as such so I had to _./launch &_ it from command line leaving me with a blocked terminal. But that's more of a note than an issue so I don't spam you with another ticket about this.

**Comment by Alamantus** [comment]
Hi there! My first thought as to why it's not moving the photos (that's all this app does—move rather than copy/recreate) is maybe it's a permissions issue with the drive(s)? I'm just using the standard Node [`fs.mkdirSync()`](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options) for creating the year/month folders and then [`fs.rename()`](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback) for moving the files, so it should work just fine unless there's a permission issue preventing it from reading the old location or writing to the new location. Far be it from me to suggest running it with `sudo`, but it might be worth a try if you're feeling risky?

The SMB share shouldn't be a problem so long as Node identifies the files as being "on your computer" and accessible via normal filesystem navigation unless the connection isn't stable... Ideally the files from Google would be actually on the computer running the program, though—that's all I tested from and it worked fine. That being said, 90GB _is_ about 3 times more files than I tested with, so you may just need to let it run for a while.

As for the executable, that's kind of an inevitability if your file explorer doesn't just launch it—Electron does allow me to export the app as a Snap or an AppImage, but these don't usually have access to the filesystem and I didn't want to bother with the trouble that would almost certainly cause. You could potentially run it in the background on your command line to keep it from locking it up? I usually just open a new terminal window (or tab depending on the emulator) when something's occupying one window though...

Finally, if this program isn't working for you and you can navigate the command line, I've been told that [this Python script](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/) does something similar to my program, just without a GUI. But I haven't tried it, so just be aware of that.

**Comment by Alamantus** [comment]
@ferreric I'm going to close this issue. If you are still having trouble _and_ still wish to use this particular app instead of another one, please let me know and I'll re-open the issue so we can discuss it some more.
